apiVersion: apps/v1

kind: Deployment

metadata:
  name: devguardian-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devguardian-demo

  template:
    metadata:
      labels:
        app: devguardian-demo

    spec:
      containers:
        - name: devguardian-container
          image: devguardian-k8s-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000